name: 'coverage'
on:
  pull_request:
    branches:
      - master
      - main
jobs:
  coverage:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v2
      - name: build container
        run: docker build -t build-image . --file Dockerfile
      - name: create tmp
        run: echo "" > /tmp/report.json
      - name: execute test
        run: docker run --volume /tmp/report.json:/home/user/src/report.json --entrypoint="npm" build-image run test:coverage
      - uses: ArtiomTr/jest-coverage-report-action@v2.0-rc.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: /tmp
          coverage-file: /tmp/report.json
          skip-step: all
